### ISSUE TITLE
Crash on rotated part copy paste

### ISSUE THREAD

**Issue by drahnr** [drahnr/oregano#127]
1. place a part on the canvas
2. <kbd>Ctrl</kbd>+<kbd>C</kbd>
3. <kbd>Ctrl</kbd>+<kbd>V</kbd>

```
../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,0.000000 to 40.000000,14.000000 - centered at 20.000000,7.000000
../../src/model/part.c:594 @ part_rotate +++ delta{group} = transform from 20.000000,10.000000 to -10.000000,20.000000
../../src/model/part.c:597 @ part_rotate +++ delta{group} = centered at 650.000000,320.000000 resulting in shift 30.000000,-10.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,0.000000 to -14.000000,40.000000 - centered at -7.000000,20.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 27.000000,-13.000000
../../src/model/part.c:664 @ part_rotate +++ 



(oregano:14928): Gtk-WARNING **: drawing failure for widget `Sheet': invalid matrix (not invertible)
```

```
#0  0x000000342f0504e9 in g_logv () from /lib64/libglib-2.0.so.0
#1  0x000000342f05063f in g_log () from /lib64/libglib-2.0.so.0
#2  0x00000030f24e760f in _gtk_widget_draw_internal.part.62 () from /lib64/libgtk-3.so.0
#3  0x00000030f24e8bef in _gtk_widget_draw_windows () from /lib64/libgtk-3.so.0
#4  0x00000030f24e8c75 in _gtk_widget_draw_windows () from /lib64/libgtk-3.so.0
#5  0x00000030f24e8e94 in _gtk_widget_draw () from /lib64/libgtk-3.so.0
#6  0x00000030f23146fd in gtk_container_propagate_draw () from /lib64/libgtk-3.so.0
#7  0x00000030f23147d2 in gtk_container_draw () from /lib64/libgtk-3.so.0
#8  0x00000030f24206dd in gtk_scrolled_window_draw () from /lib64/libgtk-3.so.0
#9  0x00000030f23ab62e in _gtk_marshal_BOOLEAN__BOXEDv () from /lib64/libgtk-3.so.0
#10 0x00000030f24d9c12 in gtk_widget_draw_marshallerv () from /lib64/libgtk-3.so.0
#11 0x000000342f81043f in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#12 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#13 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#14 0x00000030f24e74ee in _gtk_widget_draw_internal.part.62 () from /lib64/libgtk-3.so.0
#15 0x00000030f24e8bef in _gtk_widget_draw_windows () from /lib64/libgtk-3.so.0
#16 0x00000030f24e8f90 in _gtk_widget_draw () from /lib64/libgtk-3.so.0
#17 0x00000030f23146fd in gtk_container_propagate_draw () from /lib64/libgtk-3.so.0
#18 0x00000030f23147d2 in gtk_container_draw () from /lib64/libgtk-3.so.0
#19 0x00000030f23ab62e in _gtk_marshal_BOOLEAN__BOXEDv () from /lib64/libgtk-3.so.0
#20 0x00000030f24d9c12 in gtk_widget_draw_marshallerv () from /lib64/libgtk-3.so.0
#21 0x000000342f81043f in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#22 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#23 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#24 0x00000030f24e74ee in _gtk_widget_draw_internal.part.62 () from /lib64/libgtk-3.so.0
#25 0x00000030f24e8fd3 in _gtk_widget_draw () from /lib64/libgtk-3.so.0
#26 0x00000030f23146fd in gtk_container_propagate_draw () from /lib64/libgtk-3.so.0
#27 0x00000030f23147d2 in gtk_container_draw () from /lib64/libgtk-3.so.0
#28 0x00000030f23ab62e in _gtk_marshal_BOOLEAN__BOXEDv () from /lib64/libgtk-3.so.0
#29 0x00000030f24d9c12 in gtk_widget_draw_marshallerv () from /lib64/libgtk-3.so.0
#30 0x000000342f81043f in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#31 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#32 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#33 0x00000030f24e74ee in _gtk_widget_draw_internal.part.62 () from /lib64/libgtk-3.so.0
#34 0x00000030f24e8fd3 in _gtk_widget_draw () from /lib64/libgtk-3.so.0
#35 0x00000030f23146fd in gtk_container_propagate_draw () from /lib64/libgtk-3.so.0
#36 0x00000030f23147d2 in gtk_container_draw () from /lib64/libgtk-3.so.0
#37 0x00000030f23ab62e in _gtk_marshal_BOOLEAN__BOXEDv () from /lib64/libgtk-3.so.0
#38 0x00000030f24d9c12 in gtk_widget_draw_marshallerv () from /lib64/libgtk-3.so.0
#39 0x000000342f81043f in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#40 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#41 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#42 0x00000030f24e74ee in _gtk_widget_draw_internal.part.62 () from /lib64/libgtk-3.so.0
#43 0x00000030f24e8fd3 in _gtk_widget_draw () from /lib64/libgtk-3.so.0
#44 0x00000030f23146fd in gtk_container_propagate_draw () from /lib64/libgtk-3.so.0
#45 0x00000030f23147d2 in gtk_container_draw () from /lib64/libgtk-3.so.0
#46 0x00000030f23e4853 in gtk_paned_draw () from /lib64/libgtk-3.so.0
#47 0x00000030f23ab62e in _gtk_marshal_BOOLEAN__BOXEDv () from /lib64/libgtk-3.so.0
#48 0x00000030f24d9c12 in gtk_widget_draw_marshallerv () from /lib64/libgtk-3.so.0
#49 0x000000342f81043f in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#50 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#51 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#52 0x00000030f24e74ee in _gtk_widget_draw_internal.part.62 () from /lib64/libgtk-3.so.0
#53 0x00000030f24e8bef in _gtk_widget_draw_windows () from /lib64/libgtk-3.so.0
#54 0x00000030f24e8f90 in _gtk_widget_draw () from /lib64/libgtk-3.so.0
#55 0x00000030f23146fd in gtk_container_propagate_draw () from /lib64/libgtk-3.so.0
#56 0x00000030f23147d2 in gtk_container_draw () from /lib64/libgtk-3.so.0
#57 0x00000030f24fa1f4 in gtk_window_draw () from /lib64/libgtk-3.so.0
#58 0x00000030f23ab62e in _gtk_marshal_BOOLEAN__BOXEDv () from /lib64/libgtk-3.so.0
#59 0x00000030f24d9c12 in gtk_widget_draw_marshallerv () from /lib64/libgtk-3.so.0
#60 0x000000342f8104c7 in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#61 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#62 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#63 0x00000030f24e74ee in _gtk_widget_draw_internal.part.62 () from /lib64/libgtk-3.so.0
#64 0x00000030f24e8bef in _gtk_widget_draw_windows () from /lib64/libgtk-3.so.0
#65 0x00000030f24e8e94 in _gtk_widget_draw () from /lib64/libgtk-3.so.0
#66 0x00000030f24e91f3 in gtk_widget_send_expose () from /lib64/libgtk-3.so.0
#67 0x00000030f23ab455 in gtk_main_do_event () from /lib64/libgtk-3.so.0
#68 0x00000030f1e35bcb in _gdk_window_process_updates_recurse_helper () from /lib64/libgdk-3.so.0
#69 0x00000030f1e33ea5 in gdk_window_process_updates_internal () from /lib64/libgdk-3.so.0
#70 0x00000030f1e33fcd in gdk_window_process_updates_with_mode () from /lib64/libgdk-3.so.0
#71 0x000000342f8104c7 in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#72 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#73 0x000000342f82a8f8 in g_signal_emit_by_name () from /lib64/libgobject-2.0.so.0
#74 0x00000030f1e2e09e in gdk_frame_clock_paint_idle () from /lib64/libgdk-3.so.0
#75 0x00000030f1e20328 in gdk_threads_dispatch () from /lib64/libgdk-3.so.0
#76 0x000000342f049e43 in g_timeout_dispatch () from /lib64/libglib-2.0.so.0
#77 0x000000342f0492a6 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#78 0x000000342f049628 in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#79 0x000000342f0496dc in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#80 0x000000308fa9c954 in g_application_run () from /lib64/libgio-2.0.so.0
#81 0x000000000040deaa in main (argc=1, argv=0x7fffffffdff8) at ../../src/main.c:79

```

**Comment by drahnr** [comment]
For sane debugging #146 and #145 need to be fixed beforehand.

**Comment by Michi1994** [comment]
I can't replicate the crash. Could you explain in more detail how to get the crash or should it crash that simple? I can't believe it because the heading says something about "rotating" but in the steps to reproduce, there is no rotation.

**Comment by drahnr** [comment]
Same, here. I can not reproduce that issue anymore.
