### ISSUE TITLE
Crash on Clamp DnD

### ISSUE THREAD

**Issue by drahnr** [drahnr/oregano#128]
```
../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,-24.000000 to 24.000000,0.000000 - centered at 12.000000,-12.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = -7.500000,0.000000 to 7.500000,21.000000 - centered at 0.000000,10.500000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = -7.500000,0.000000 to 7.500000,21.000000 - centered at 0.000000,10.500000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = -5.000000,0.000000 to 25.000000,40.000000 - centered at 10.000000,20.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = -5.000000,0.000000 to 25.000000,40.000000 - centered at 10.000000,20.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,0.000000 to 20.000000,40.000000 - centered at 10.000000,20.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,0.000000 to 20.000000,40.000000 - centered at 10.000000,20.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,0.000000 to 40.000000,14.000000 - centered at 20.000000,7.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,0.000000 to 40.000000,14.000000 - centered at 20.000000,7.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,0.000000 to 40.000000,14.000000 - centered at 20.000000,7.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,0.000000 to 40.000000,14.000000 - centered at 20.000000,7.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 


../../src/model/part.c:581 @ part_rotate +++ bbox[vanilla] = 0.000000,0.000000 to 20.000000,40.000000 - centered at 10.000000,20.000000
../../src/model/part.c:635 @ part_rotate +++ bbox[trans] = 0.000000,0.000000 to 20.000000,40.000000 - centered at 10.000000,20.000000
../../src/model/part.c:636 @ part_rotate +++ bbox[delta] = 0.000000,0.000000
../../src/model/part.c:662 @ part_rotate +++ handler not yet registerd.
../../src/model/part.c:664 @ part_rotate +++ 



** (oregano:15151): WARNING **: Could not remove pin[0] from node 0x12969e0.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x000000342f0504e9 in g_logv () from /lib64/libglib-2.0.so.0
Missing separate debuginfos, use: debuginfo-install GConf2-3.2.6-7.fc20.x86_64 at-spi2-atk-2.10.2-1.fc20.x86_64 at-spi2-core-2.10.2-1.fc20.x86_64 atk-2.10.0-1.fc20.x86_64 cairo-1.13.1-0.1.git337ab1f.fc20.x86_64 cairo-gobject-1.13.1-0.1.git337ab1f.fc20.x86_64 dbus-glib-0.100.2-2.fc20.x86_64 dbus-libs-1.6.12-9.fc20.x86_64 dconf-0.18.0-2.fc20.x86_64 expat-2.1.0-7.fc20.x86_64 fontconfig-2.11.0-2.fc20.x86_64 freetype-2.5.0-5.fc20.x86_64 gdk-pixbuf2-2.30.3-1.fc20.x86_64 glib2-2.38.2-2.fc20.x86_64 glibc-2.18-12.fc20.x86_64 goocanvas2-2.0.1-6.8f2c63git.fc20.x86_64 gtk3-3.10.9-1.fc20.x86_64 gtksourceview3-3.10.3-1.fc20.x86_64 gvfs-1.18.3-2.fc20.x86_64 harfbuzz-0.9.27-1.fc20.x86_64 libX11-1.6.1-1.fc20.x86_64 libXau-1.0.8-2.fc20.x86_64 libXcomposite-0.4.4-4.fc20.x86_64 libXcursor-1.1.14-2.fc20.x86_64 libXdamage-1.1.4-4.fc20.x86_64 libXext-1.3.2-2.fc20.x86_64 libXfixes-5.0.1-2.fc20.x86_64 libXi-1.7.4-1.fc20.x86_64 libXinerama-1.1.3-2.fc20.x86_64 libXrandr-1.4.1-2.fc20.x86_64 libXrender-0.9.8-2.fc20.x86_64 libbluray-0.6.0-1.fc20.x86_64 libdrm-2.4.54-1.fc20.x86_64 libffi-3.0.13-5.fc20.x86_64 libgcc-4.8.3-1.fc20.x86_64 libpng-1.6.6-3.fc20.x86_64 libselinux-2.2.1-6.fc20.x86_64 libwayland-client-1.2.0-3.fc20.x86_64 libwayland-cursor-1.2.0-3.fc20.x86_64 libwayland-server-1.2.0-3.fc20.x86_64 libxcb-1.9.1-3.fc20.x86_64 libxkbcommon-0.3.1-1.fc20.x86_64 libxml2-2.9.1-2.fc20.x86_64 mesa-libEGL-10.1.5-1.20140607.fc20.x86_64 mesa-libgbm-10.1.5-1.20140607.fc20.x86_64 mesa-libglapi-10.1.5-1.20140607.fc20.x86_64 pango-1.36.1-3.fc20.x86_64 pcre-8.33-6.fc20.x86_64 pixman-0.30.0-3.fc20.x86_64 systemd-libs-208-21.fc20.x86_64 xz-libs-5.1.2-12alpha.fc20.x86_64 zlib-1.2.8-3.fc20.x86_64
(gdb) bt
#0  0x000000342f0504e9 in g_logv () from /lib64/libglib-2.0.so.0
#1  0x000000342f05063f in g_log () from /lib64/libglib-2.0.so.0
#2  0x000000000042316a in node_store_remove_part (self=0xed5e80, part=0x1296de0) at ../../src/model/node-store.c:303
#3  0x0000000000428eac in part_unregister (data=0x1296de0) at ../../src/model/part.c:940
#4  0x000000000042062c in item_data_unregister (data=0x1296de0) at ../../src/model/item-data.c:505
#5  0x000000000041f07b in item_data_dispose (object=0x1296de0) at ../../src/model/item-data.c:103
#6  0x000000000042683f in part_dispose (object=0x1296de0) at ../../src/model/part.c:111
#7  0x000000342f814ee8 in g_object_unref () from /lib64/libgobject-2.0.so.0
#8  0x000000000044aafc in sheet_remove_item_in_sheet (item=0x1097360, sheet=0xd0e3b0) at ../../src/sheet/sheet.c:1475
#9  0x00000000004493a8 in sheet_delete_selection (sheet=0xd0e3b0) at ../../src/sheet/sheet.c:1080
#10 0x0000000000448c98 in sheet_event_callback (widget=0xd0e3b0, event=0x12195e0, sheet=0xd0e3b0) at ../../src/sheet/sheet.c:935
#11 0x00000030f23ab62e in _gtk_marshal_BOOLEAN__BOXEDv () from /lib64/libgtk-3.so.0
#12 0x000000342f8104c7 in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#13 0x000000342f829749 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#14 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#15 0x00000030f24dd305 in gtk_widget_event_internal () from /lib64/libgtk-3.so.0
#16 0x00000030f24fb18b in gtk_window_propagate_key_event () from /lib64/libgtk-3.so.0
#17 0x00000030f24fde5b in gtk_window_key_press_event () from /lib64/libgtk-3.so.0
#18 0x00000030f23ab52c in _gtk_marshal_BOOLEAN__BOXED () from /lib64/libgtk-3.so.0
#19 0x000000342f810298 in g_closure_invoke () from /lib64/libgobject-2.0.so.0
#20 0x000000342f82211b in signal_emit_unlocked_R () from /lib64/libgobject-2.0.so.0
#21 0x000000342f829ddd in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#22 0x000000342f82a3af in g_signal_emit () from /lib64/libgobject-2.0.so.0
#23 0x00000030f24dd37c in gtk_widget_event_internal () from /lib64/libgtk-3.so.0
#24 0x00000030f23a9a2f in propagate_event () from /lib64/libgtk-3.so.0
#25 0x00000030f23ab1ea in gtk_main_do_event () from /lib64/libgtk-3.so.0
#26 0x00000030f1e4ef62 in gdk_event_source_dispatch () from /lib64/libgdk-3.so.0
#27 0x000000342f0492a6 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#28 0x000000342f049628 in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#29 0x000000342f0496dc in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#30 0x000000308fa9c954 in g_application_run () from /lib64/libgio-2.0.so.0
#31 0x000000000040deaa in main (argc=1, argv=0x7fffffffdff8) at ../../src/main.c:79

```

**Comment by drahnr** [comment]
It's ridiculous how fast time passes by. 1 year bug anniversary.

**Comment by drahnr** [comment]
Also: Maybe just get rid of the testclamp altogether? Or transform it into a tool?
