### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by flok99** [drahnr/oregano#237]
```
0x0000555555597572 in log_append_trim_message (string=0x7fffd4001f10 "") at ../src/log.c:42
42		if (*ret_val == 0) {
(gdb) bt
#0  0x0000555555597572 in log_append_trim_message (string=0x7fffd4001f10 "") at ../src/log.c:42
#1  0x00005555555975c5 in log_append (log=0x5555560024f0, prefix=0x5555555ee004 "simulation engine Error", message=0x7fffd4001f10 "") at ../src/log.c:60
#2  0x00005555555a59c3 in schematic_log_append_error (schematic=0x555555896720, message=0x7fffd4001f10 "") at ../src/model/schematic.c:528
#3  0x000055555558ba35 in print_additional_info (log=..., ngspice_result_file=0x555555fb8b00 "/tmp/netlist.lst", netlist_file=0x555555fb8b20 "/tmp/netlist.tmp")
    at ../src/engines/ngspice-watcher.c:276
#4  0x000055555558bcad in ngspice_watcher_watch_ngspice_resources (pid=15304, status=256, resources=0x555555fb8a80) at ../src/engines/ngspice-watcher.c:346
#5  0x000055555558bdb9 in ngspice_watcher_watch_ngspice (pid=15304, status=256, resources=0x555555fb8a80) at ../src/engines/ngspice-watcher.c:383
#6  0x00007ffff7b38454 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7b3bae8 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7b3bed8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff7b3c1d2 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x000055555558b69c in ngspice_watcher_main (main_loop=0x555555f99db0) at ../src/engines/ngspice-watcher.c:177
#11 0x00007ffff7b64135 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff6013164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#13 0x00007ffff6bc4def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by drahnr** [comment]
Thanks for reporting!
